"use client";
import { useState } from "react";
import { Copy, FileDown, FilePlus2, ShieldCheck } from "lucide-react";
import DashboardShell, { type DashboardShellSummary } from "@/components/dashboard/dashboard-shell";
import ClientReportContent from "@/components/client-report-content";
import type { ClientReport } from "@/lib/types";

export default function ClientReportsDashboard({ initialReports, shellSummary }: { initialReports: ClientReport[]; shellSummary: DashboardShellSummary }) {
  const [reports, setReports] = useState(initialReports); const [selected, setSelected] = useState<ClientReport | null>(initialReports[0] ?? null); const [shareUrl, setShareUrl] = useState<string | null>(null); const [expiresAt, setExpiresAt] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function call(path: string, init: RequestInit = {}) { setPending(true); setError(null); const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init.headers } }); const data = await response.json().catch(() => null); setPending(false); if (!response.ok) { setError(data?.detail ?? "Report action failed."); return null; } return data; }
  async function create() { const data = await call(`/api/projects/${shellSummary.project_id}/client-reports`, { method: "POST", body: JSON.stringify({ title: `${shellSummary.target.brand} Search Intelligence Report` }) }); if (data) { setReports((v) => [data, ...v]); setSelected(data); setShareUrl(null); } }
  async function publish(report: ClientReport) { const data = await call(`/api/projects/${report.project_id}/client-reports/${report.id}/publish`, { method: "POST", body: JSON.stringify({ expires_at: expiresAt ? new Date(expiresAt).toISOString() : null }) }); if (data) { const { share_token, ...clean } = data; const updated = clean as ClientReport; setReports((v) => v.map((x) => x.id === updated.id ? updated : x)); setSelected(updated); setShareUrl(`${location.origin}/client-reports/share/${share_token}`); } }
  async function state(report: ClientReport, action: "unpublish" | "revoke") { const data = await call(`/api/projects/${report.project_id}/client-reports/${report.id}/${action}`, { method: "POST", body: "{}" }); if (data) { setReports((v) => v.map((x) => x.id === data.id ? data : x)); setSelected(data); setShareUrl(null); } }
  return <DashboardShell summary={shellSummary} title="Client Reports"><div className="crystal-page mx-auto max-w-[1450px] space-y-6 p-5 lg:p-8"><section className="crystal-panel rounded-[22px] p-7"><div className="flex flex-wrap justify-between gap-5"><div><div className="crystal-eyebrow">Immutable client deliverables</div><h2 className="mt-3 text-2xl font-medium">Snapshots, sharing, and PDF from one evidence model</h2><p className="mt-2 text-sm text-slate-500">Creating a report captures stored evidence without running AI, search, crawls, or benchmarks.</p></div><button disabled={pending} onClick={create} className="crystal-primary-button flex items-center gap-2 px-4 py-2.5"><FilePlus2 className="h-4 w-4" />Create report</button></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}</section>
    <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><aside className="space-y-3">{reports.map((r) => <button key={r.id} onClick={() => { setSelected(r); setShareUrl(null); setExpiresAt(""); }} className="crystal-panel w-full rounded-2xl p-5 text-left"><div className="font-medium">{r.title}</div><div className="mt-2 text-xs text-slate-500">{new Date(r.created_at).toLocaleDateString()} · {r.status.toUpperCase()}{r.expires_at && new Date(r.expires_at) <= new Date() ? " · EXPIRED" : ""}</div></button>)}{reports.length === 0 && <div className="crystal-panel rounded-2xl p-6 text-sm text-slate-500">No report snapshots yet.</div>}</aside><div>{selected && <><div className="mb-4 flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-4">{selected.status !== "published" ? <><label className="flex items-center gap-2 text-xs text-slate-500">Optional expiry <input type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-700" /></label><button disabled={pending} onClick={() => publish(selected)} className="crystal-primary-button px-4 py-2 text-sm">Publish & issue private link</button></> : <><button disabled={pending} onClick={() => state(selected, "unpublish")} className="rounded-xl border px-4 py-2 text-sm">Unpublish</button><button disabled={pending} onClick={() => state(selected, "revoke")} className="rounded-xl border border-red-200 px-4 py-2 text-sm text-red-700">Revoke</button></>}<a href={`/api/projects/${selected.project_id}/client-reports/${selected.id}/pdf`} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm"><FileDown className="h-4 w-4" />Export PDF</a>{shareUrl && <button onClick={() => navigator.clipboard.writeText(shareUrl)} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm"><Copy className="h-4 w-4" />Copy private link</button>}<span className="ml-auto flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-4 w-4" />Token stored as hash only</span></div><ClientReportContent report={selected} /></>}</div></div></div></DashboardShell>;
}
