"use client";

import { useState } from "react";
import { Pause, Play, ShieldCheck } from "lucide-react";
import DashboardShell, { type DashboardShellSummary } from "@/components/dashboard/dashboard-shell";
import type { MonitoringSchedule, MonitoringSummary } from "@/lib/types";
import { estimatedMonthlyRuns, monitoringConfirmation } from "@/lib/monitoring-safety";

const labels: Record<string, string> = { technical_seo: "Technical SEO", memory: "Memory", web_search: "Web Search", site_rag: "Site RAG" };
const descriptions: Record<string, string> = { technical_seo: "Bounded crawl and technical audit", memory: "Latent model knowledge using frozen prompts", web_search: "Controlled paid API web-search measurement", site_rag: "First-party crawled-site answerability" };
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value: string | null) => value ? new Date(value).toLocaleString() : "Never";

export default function MonitoringDashboard({ initial, operatorAuthorized, shellSummary }: { initial: MonitoringSummary; operatorAuthorized: boolean; shellSummary: DashboardShellSummary }) {
  const [summary, setSummary] = useState(initial); const [pending, setPending] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [drafts, setDrafts] = useState<Record<string, { cadence: number; source: number | null; runAfterCrawl: boolean }>>(() => Object.fromEntries(initial.schedules.map((item) => [item.mode, { cadence: item.cadence_hours, source: item.source_benchmark_job_id ?? initial.compatible_sources.find((source) => source.mode === item.mode)?.id ?? null, runAfterCrawl: item.run_after_crawl }])));
  const update = async (schedule: MonitoringSchedule, enabled: boolean) => {
    const draft = drafts[schedule.mode];
    const source = summary.compatible_sources.find((item) => item.id === draft?.source);
    if (schedule.mode !== "technical_seo" && !source) { setError(`No compatible completed ${labels[schedule.mode]} benchmark is available as a frozen source.`); return; }
    if (enabled && ["memory", "web_search"].includes(schedule.mode)) {
      const confirmation = monitoringConfirmation({ mode: schedule.mode, modelId: source!.model_id, promptCount: source!.prompt_count, cadenceHours: draft.cadence });
      if (!window.confirm(`Enable scheduled ${labels[schedule.mode]}?\n\nModel ID: ${confirmation.modelId}\nFrozen prompts: ${confirmation.promptCount}\nRuns per check: ${confirmation.runsPerCheck}\nCadence: every ${confirmation.cadenceHours} hours\nEstimated monthly AI runs: ${confirmation.estimatedMonthlyRuns}\nWeb Search: ${confirmation.webSearchEnabled ? "Enabled" : "Disabled"}`)) return;
    }
    setPending(schedule.mode); setError(null);
    const response = await fetch(`/api/projects/${summary.project_id}/monitoring/${schedule.mode}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled, cadence_hours: draft.cadence, source_benchmark_job_id: source?.id ?? null, run_after_crawl: draft.runAfterCrawl, paid_execution_confirmed: enabled && ["memory", "web_search"].includes(schedule.mode) }) });
    const body = await response.json(); if (!response.ok) setError(body.detail ?? "Could not update monitoring."); else setSummary((current) => ({ ...current, schedules: current.schedules.map((item) => item.mode === schedule.mode ? body : item) })); setPending(null);
  };
  return <DashboardShell summary={shellSummary} title="Monitoring"><main className="crystal-page mx-auto max-w-[1450px] space-y-6 p-5 lg:p-8">
    <section className="crystal-panel rounded-[22px] p-7"><div className="crystal-eyebrow">Durable measurement operations</div><h2 className="mt-3 text-2xl font-medium">Scheduled checks and compatible change detection</h2><p className="mt-2 max-w-3xl text-sm text-slate-500">Schedules are persisted in PostgreSQL and claimed by a restart-safe worker. Historical measurements are preserved; loading this page never runs a measurement.</p>
      <div className="mt-6 grid gap-3 sm:grid-cols-5"><Metric title="Needs attention" value={summary.agency.needs_attention} tone={summary.agency.needs_attention ? "warn" : "ok"}/><Metric title="Due" value={summary.agency.due}/><Metric title="Overdue" value={summary.agency.overdue}/><Metric title="Failed" value={summary.agency.failed} tone={summary.agency.failed ? "warn" : undefined}/><Metric title="Recently improved" value={summary.agency.recently_improved} tone="ok"/></div></section>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="grid gap-5 xl:grid-cols-2">{summary.schedules.map((schedule) => { const source = summary.compatible_sources.find((item) => item.id === schedule.source_benchmark_job_id) ?? summary.compatible_sources.find((item) => item.mode === schedule.mode); return <article key={schedule.mode} className="crystal-panel rounded-[22px] p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-medium">{labels[schedule.mode]}</h3><p className="mt-1 text-sm text-slate-500">{descriptions[schedule.mode]}</p></div><span className={`rounded-full px-3 py-1 text-xs font-medium ${schedule.enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{schedule.enabled ? "ENABLED" : "PAUSED"}</span></div>
      <dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><Data label="State" value={pretty(schedule.state)}/><Data label="Cadence" value={`Every ${schedule.cadence_hours} hours`}/><Data label="Last successful" value={date(schedule.last_successful_at)}/><Data label="Next due" value={date(schedule.next_due_at)}/><Data label="Latest change" value={String(schedule.last_result.classification ? pretty(String(schedule.last_result.classification)) : "No comparison yet")}/><Data label="Frozen prompts" value={source ? `${source.prompt_count} · model ${source.model_id}` : schedule.mode === "technical_seo" ? "Not applicable" : "Select a completed source"}/></dl>
      {operatorAuthorized && !schedule.enabled && <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Cadence<select value={drafts[schedule.mode].cadence} onChange={(event) => setDrafts((current) => ({ ...current, [schedule.mode]: { ...current[schedule.mode], cadence: Number(event.target.value) } }))} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700"><option value={24}>Daily</option><option value={168}>Weekly</option><option value={336}>Every two weeks</option><option value={720}>Monthly</option></select></label>{schedule.mode !== "technical_seo" && <label className="text-xs text-slate-500">Approved frozen measurement<select value={drafts[schedule.mode].source ?? ""} onChange={(event) => setDrafts((current) => ({ ...current, [schedule.mode]: { ...current[schedule.mode], source: Number(event.target.value) } }))} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700"><option value="">Select benchmark</option>{summary.compatible_sources.filter((item) => item.mode === schedule.mode).map((item) => <option key={item.id} value={item.id}>#{item.id} · {item.prompt_count} prompts · model {item.model_id}</option>)}</select></label>}</div>}
      {operatorAuthorized && !schedule.enabled && schedule.mode === "site_rag" && <label className="mt-3 flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={drafts[schedule.mode].runAfterCrawl} onChange={(event) => setDrafts((current) => ({ ...current, [schedule.mode]: { ...current[schedule.mode], runAfterCrawl: event.target.checked } }))}/>Run this compatible Site RAG recheck after a successful scheduled crawl.</label>}
      {schedule.failure_message && <p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700">{schedule.failure_message}</p>}
      {schedule.mode !== "technical_seo" && source && <div className="mt-4 rounded-xl bg-indigo-50 p-3 text-xs text-indigo-700"><ShieldCheck className="mr-1 inline h-4 w-4"/>Expected {source.prompt_count} runs/check · approximately {estimatedMonthlyRuns(source.prompt_count, schedule.cadence_hours)} runs/month · Web Search {schedule.mode === "web_search" ? "enabled" : "disabled"}.</div>}
      {operatorAuthorized ? <button disabled={pending === schedule.mode} onClick={() => update(schedule, !schedule.enabled)} className="crystal-primary-button mt-5 flex items-center gap-2 px-4 py-2 text-sm">{schedule.enabled ? <Pause className="h-4 w-4"/> : <Play className="h-4 w-4"/>}{schedule.enabled ? "Pause" : "Configure & enable"}</button> : <p className="mt-5 text-xs text-slate-400">Operator authorization is required to change schedules.</p>}</article>; })}</section>
    <section className="crystal-panel rounded-[22px] p-6"><h3 className="text-lg font-medium">Scheduled execution history</h3><div className="mt-4 space-y-3">{summary.runs.map((run) => <div key={run.id} className="grid gap-2 rounded-xl border border-slate-100 p-4 text-sm md:grid-cols-5"><span>{labels[run.mode] ?? pretty(run.mode)}</span><span>{pretty(run.status)}</span><span>{run.change_classification ? pretty(run.change_classification) : "No change result"}</span><span>{date(run.started_at)}</span><span className="text-slate-500">{run.error_message ?? "Completed without worker error"}</span></div>)}{summary.runs.length === 0 && <p className="text-sm text-slate-500">No scheduled executions yet.</p>}</div></section>
  </main></DashboardShell>;
}

function Metric({ title, value, tone }: { title: string; value: number; tone?: string }) { return <div className="rounded-2xl bg-white/70 p-4"><div className="text-xs text-slate-400">{title}</div><div className={`mt-2 text-2xl ${tone === "warn" ? "text-amber-600" : tone === "ok" ? "text-emerald-600" : "text-slate-900"}`}>{value}</div></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-slate-700">{value}</dd></div>; }
