"""add technical seo audits

Revision ID: 0f71614fa2c3
Revises: b458996b8533
Create Date: 2026-08-23 23:38:30.411461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f71614fa2c3'
down_revision: Union[str, Sequence[str], None] = 'b458996b8533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('pages_checked', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_audits_website_id'), 'technical_audits', ['website_id'], unique=False)
    op.create_table('technical_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['technical_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_issues_audit_id'), 'technical_issues', ['audit_id'], unique=False)
    op.create_index(op.f('ix_technical_issues_code'), 'technical_issues', ['code'], unique=False)
    op.create_index(op.f('ix_technical_issues_page_id'), 'technical_issues', ['page_id'], unique=False)
    op.create_index(op.f('ix_technical_issues_severity'), 'technical_issues', ['severity'], unique=False)
    op.add_column(
        'pages',
        sa.Column('h1_count', sa.Integer(), nullable=True)
    )

    op.execute(
        "UPDATE pages SET h1_count = 0 "
        "WHERE h1_count IS NULL"
    )

    op.alter_column(
        'pages',
        'h1_count',
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'h1_count')
    op.drop_index(op.f('ix_technical_issues_severity'), table_name='technical_issues')
    op.drop_index(op.f('ix_technical_issues_page_id'), table_name='technical_issues')
    op.drop_index(op.f('ix_technical_issues_code'), table_name='technical_issues')
    op.drop_index(op.f('ix_technical_issues_audit_id'), table_name='technical_issues')
    op.drop_table('technical_issues')
    op.drop_index(op.f('ix_technical_audits_website_id'), table_name='technical_audits')
    op.drop_table('technical_audits')
    # ### end Alembic commands ###
