"""add entity hierarchy foundation

Revision ID: 12e12506dc9a
Revises: d078c217bc8d
Create Date: 2026-08-24 15:32:03.703933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e12506dc9a'
down_revision: Union[str, Sequence[str], None] = 'd078c217bc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('rollup_brand_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rollup_brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_entities_entity_type'), 'search_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_search_entities_normalized_name'), 'search_entities', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_search_entities_rollup_brand_id'), 'search_entities', ['rollup_brand_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['search_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_entity_alias')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_normalized_alias'), 'entity_aliases', ['normalized_alias'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_entity_id', sa.Integer(), nullable=False),
    sa.Column('object_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['search_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['search_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_entity_id', 'object_entity_id', 'relationship_type', name='uq_entity_relationship')
    )
    op.create_index(op.f('ix_entity_relationships_object_entity_id'), 'entity_relationships', ['object_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_relationship_type'), 'entity_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_entity_relationships_subject_entity_id'), 'entity_relationships', ['subject_entity_id'], unique=False)
    op.add_column('brand_mentions', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_brand_mentions_entity_id'), 'brand_mentions', ['entity_id'], unique=False)
    op.create_foreign_key(None, 'brand_mentions', 'search_entities', ['entity_id'], ['id'], ondelete='SET NULL')
    op.add_column('citations', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_citations_entity_id'), 'citations', ['entity_id'], unique=False)
    op.create_foreign_key(None, 'citations', 'search_entities', ['entity_id'], ['id'], ondelete='SET NULL')
    op.add_column('entity_resolution_rules', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('entity_resolution_rules', sa.Column('entity_type', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_entity_resolution_rules_entity_id'), 'entity_resolution_rules', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_resolution_rules_entity_type'), 'entity_resolution_rules', ['entity_type'], unique=False)
    op.create_foreign_key(None, 'entity_resolution_rules', 'search_entities', ['entity_id'], ['id'], ondelete='SET NULL')
    op.add_column('web_search_sources', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_web_search_sources_entity_id'), 'web_search_sources', ['entity_id'], unique=False)
    op.create_foreign_key(None, 'web_search_sources', 'search_entities', ['entity_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_search_sources', type_='foreignkey')
    op.drop_index(op.f('ix_web_search_sources_entity_id'), table_name='web_search_sources')
    op.drop_column('web_search_sources', 'entity_id')
    op.drop_constraint(None, 'entity_resolution_rules', type_='foreignkey')
    op.drop_index(op.f('ix_entity_resolution_rules_entity_type'), table_name='entity_resolution_rules')
    op.drop_index(op.f('ix_entity_resolution_rules_entity_id'), table_name='entity_resolution_rules')
    op.drop_column('entity_resolution_rules', 'entity_type')
    op.drop_column('entity_resolution_rules', 'entity_id')
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.drop_index(op.f('ix_citations_entity_id'), table_name='citations')
    op.drop_column('citations', 'entity_id')
    op.drop_constraint(None, 'brand_mentions', type_='foreignkey')
    op.drop_index(op.f('ix_brand_mentions_entity_id'), table_name='brand_mentions')
    op.drop_column('brand_mentions', 'entity_id')
    op.drop_index(op.f('ix_entity_relationships_subject_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_relationship_type'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_object_entity_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entity_aliases_normalized_alias'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_search_entities_rollup_brand_id'), table_name='search_entities')
    op.drop_index(op.f('ix_search_entities_normalized_name'), table_name='search_entities')
    op.drop_index(op.f('ix_search_entities_entity_type'), table_name='search_entities')
    op.drop_table('search_entities')
    # ### end Alembic commands ###
