"""add brand aliases

Revision ID: 16e231176d65
Revises: f410c151349f
Create Date: 2026-08-24 10:02:17.684731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e231176d65'
down_revision: Union[str, Sequence[str], None] = 'f410c151349f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_aliases_brand_id'), 'brand_aliases', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_aliases_normalized_alias'), 'brand_aliases', ['normalized_alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_aliases_normalized_alias'), table_name='brand_aliases')
    op.drop_index(op.f('ix_brand_aliases_brand_id'), table_name='brand_aliases')
    op.drop_table('brand_aliases')
    # ### end Alembic commands ###
