"""add geo prompt opportunities

Revision ID: 1b5ab02e43b4
Revises: 8fe305047aef
Create Date: 2026-08-24 10:48:32.601625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5ab02e43b4'
down_revision: Union[str, Sequence[str], None] = '8fe305047aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_prompt_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('target_brand_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('target_mention_runs', sa.Integer(), nullable=False),
    sa.Column('target_mention_rate', sa.Float(), nullable=False),
    sa.Column('top_competitor_brand_id', sa.Integer(), nullable=True),
    sa.Column('top_competitor_name', sa.String(length=255), nullable=True),
    sa.Column('top_competitor_run_coverage', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('gap_type', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['geo_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['top_competitor_brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'prompt_id', name='uq_experiment_prompt_opportunity')
    )
    op.create_index(op.f('ix_geo_prompt_opportunities_category'), 'geo_prompt_opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_experiment_id'), 'geo_prompt_opportunities', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_gap_type'), 'geo_prompt_opportunities', ['gap_type'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_priority'), 'geo_prompt_opportunities', ['priority'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_project_id'), 'geo_prompt_opportunities', ['project_id'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_prompt_id'), 'geo_prompt_opportunities', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_target_brand_id'), 'geo_prompt_opportunities', ['target_brand_id'], unique=False)
    op.create_index(op.f('ix_geo_prompt_opportunities_top_competitor_brand_id'), 'geo_prompt_opportunities', ['top_competitor_brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geo_prompt_opportunities_top_competitor_brand_id'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_target_brand_id'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_prompt_id'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_project_id'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_priority'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_gap_type'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_experiment_id'), table_name='geo_prompt_opportunities')
    op.drop_index(op.f('ix_geo_prompt_opportunities_category'), table_name='geo_prompt_opportunities')
    op.drop_table('geo_prompt_opportunities')
    # ### end Alembic commands ###
