"""add evidence grounded geo content diagnoses

Revision ID: 282fa43ed740
Revises: 1b5ab02e43b4
Create Date: 2026-08-24 11:09:59.024737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282fa43ed740'
down_revision: Union[str, Sequence[str], None] = '1b5ab02e43b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_content_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_brand_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('evidence_page_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_run_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['geo_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['geo_prompt_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_content_diagnoses_created_at'), 'geo_content_diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_geo_content_diagnoses_experiment_id'), 'geo_content_diagnoses', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_geo_content_diagnoses_model_id'), 'geo_content_diagnoses', ['model_id'], unique=False)
    op.create_index(op.f('ix_geo_content_diagnoses_opportunity_id'), 'geo_content_diagnoses', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_geo_content_diagnoses_project_id'), 'geo_content_diagnoses', ['project_id'], unique=False)
    op.create_index(op.f('ix_geo_content_diagnoses_target_brand_id'), 'geo_content_diagnoses', ['target_brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geo_content_diagnoses_target_brand_id'), table_name='geo_content_diagnoses')
    op.drop_index(op.f('ix_geo_content_diagnoses_project_id'), table_name='geo_content_diagnoses')
    op.drop_index(op.f('ix_geo_content_diagnoses_opportunity_id'), table_name='geo_content_diagnoses')
    op.drop_index(op.f('ix_geo_content_diagnoses_model_id'), table_name='geo_content_diagnoses')
    op.drop_index(op.f('ix_geo_content_diagnoses_experiment_id'), table_name='geo_content_diagnoses')
    op.drop_index(op.f('ix_geo_content_diagnoses_created_at'), table_name='geo_content_diagnoses')
    op.drop_table('geo_content_diagnoses')
    # ### end Alembic commands ###
