"""add entity classification metadata

Revision ID: 3112810a77bd
Revises: 12e12506dc9a
Create Date: 2026-08-24 15:48:15.704121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3112810a77bd'
down_revision: Union[str, Sequence[str], None] = '12e12506dc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_resolution_rules', sa.Column('proposed_parent_name', sa.String(length=255), nullable=True))
    op.add_column('entity_resolution_rules', sa.Column('proposed_relationship_type', sa.String(length=40), nullable=True))
    op.add_column('entity_resolution_rules', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('entity_resolution_rules', sa.Column('classification_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_resolution_rules', 'classification_source')
    op.drop_column('entity_resolution_rules', 'classification_confidence')
    op.drop_column('entity_resolution_rules', 'proposed_relationship_type')
    op.drop_column('entity_resolution_rules', 'proposed_parent_name')
    # ### end Alembic commands ###
