"""add visibility analysis version

Revision ID: 48cfcd072322
Revises: 3112810a77bd
Create Date: 2026-08-26 08:28:07.706418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cfcd072322'
down_revision: Union[str, Sequence[str], None] = '3112810a77bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('visibility_analysis_version', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_responses', 'visibility_analysis_version')
    # ### end Alembic commands ###
