"""add technical seo recommendations

Revision ID: 7708e4ae926d
Revises: 0f71614fa2c3
Create Date: 2026-08-24 00:02:33.807432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7708e4ae926d'
down_revision: Union[str, Sequence[str], None] = '0f71614fa2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['technical_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['technical_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'issue_id', name='uq_audit_issue_recommendation')
    )
    op.create_index(op.f('ix_technical_recommendations_audit_id'), 'technical_recommendations', ['audit_id'], unique=False)
    op.create_index(op.f('ix_technical_recommendations_issue_code'), 'technical_recommendations', ['issue_code'], unique=False)
    op.create_index(op.f('ix_technical_recommendations_issue_id'), 'technical_recommendations', ['issue_id'], unique=False)
    op.create_index(op.f('ix_technical_recommendations_page_id'), 'technical_recommendations', ['page_id'], unique=False)
    op.create_index(op.f('ix_technical_recommendations_priority'), 'technical_recommendations', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_recommendations_priority'), table_name='technical_recommendations')
    op.drop_index(op.f('ix_technical_recommendations_page_id'), table_name='technical_recommendations')
    op.drop_index(op.f('ix_technical_recommendations_issue_id'), table_name='technical_recommendations')
    op.drop_index(op.f('ix_technical_recommendations_issue_code'), table_name='technical_recommendations')
    op.drop_index(op.f('ix_technical_recommendations_audit_id'), table_name='technical_recommendations')
    op.drop_table('technical_recommendations')
    # ### end Alembic commands ###
