"""add prioritized geo action plans

Revision ID: 790eff6cfd5c
Revises: 282fa43ed740
Create Date: 2026-08-24 11:36:05.146263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790eff6cfd5c'
down_revision: Union[str, Sequence[str], None] = '282fa43ed740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_brand_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=False),
    sa.Column('baseline_metrics', sa.JSON(), nullable=False),
    sa.Column('source_diagnosis_ids', sa.JSON(), nullable=False),
    sa.Column('recommended_sequence', sa.JSON(), nullable=False),
    sa.Column('risks_and_limits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['geo_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_action_plans_created_at'), 'geo_action_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_geo_action_plans_experiment_id'), 'geo_action_plans', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_geo_action_plans_project_id'), 'geo_action_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_geo_action_plans_target_brand_id'), 'geo_action_plans', ['target_brand_id'], unique=False)
    op.create_table('geo_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_plan_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_page', sa.String(length=500), nullable=True),
    sa.Column('impacted_prompt_ids', sa.JSON(), nullable=False),
    sa.Column('impacted_opportunity_ids', sa.JSON(), nullable=False),
    sa.Column('implementation_steps', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('success_metrics', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['geo_action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_action_items_action_plan_id'), 'geo_action_items', ['action_plan_id'], unique=False)
    op.create_index(op.f('ix_geo_action_items_action_type'), 'geo_action_items', ['action_type'], unique=False)
    op.create_index(op.f('ix_geo_action_items_priority'), 'geo_action_items', ['priority'], unique=False)
    op.create_index(op.f('ix_geo_action_items_status'), 'geo_action_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geo_action_items_status'), table_name='geo_action_items')
    op.drop_index(op.f('ix_geo_action_items_priority'), table_name='geo_action_items')
    op.drop_index(op.f('ix_geo_action_items_action_type'), table_name='geo_action_items')
    op.drop_index(op.f('ix_geo_action_items_action_plan_id'), table_name='geo_action_items')
    op.drop_table('geo_action_items')
    op.drop_index(op.f('ix_geo_action_plans_target_brand_id'), table_name='geo_action_plans')
    op.drop_index(op.f('ix_geo_action_plans_project_id'), table_name='geo_action_plans')
    op.drop_index(op.f('ix_geo_action_plans_experiment_id'), table_name='geo_action_plans')
    op.drop_index(op.f('ix_geo_action_plans_created_at'), table_name='geo_action_plans')
    op.drop_table('geo_action_plans')
    # ### end Alembic commands ###
