"""add visibility analysis tracking and metric snapshots

Revision ID: a7ad1d17ed43
Revises: f443a7baebe9
Create Date: 2026-08-24 01:26:20.903090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ad1d17ed43'
down_revision: Union[str, Sequence[str], None] = 'f443a7baebe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_brand_id'), 'metric_snapshots', ['brand_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_metric_name'), 'metric_snapshots', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_project_id'), 'metric_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_snapshot_at'), 'metric_snapshots', ['snapshot_at'], unique=False)
    op.add_column('ai_responses', sa.Column('visibility_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_responses', 'visibility_analyzed_at')
    op.drop_index(op.f('ix_metric_snapshots_snapshot_at'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_project_id'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_metric_name'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_brand_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
