"""add site rag source evidence

Revision ID: af134a8ac2c9
Revises: 48cfcd072322
Create Date: 2026-08-26 18:19:59.545349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af134a8ac2c9'
down_revision: Union[str, Sequence[str], None] = '48cfcd072322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_rag_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'rank', name='uq_site_rag_source_rank')
    )
    op.create_index(op.f('ix_site_rag_sources_page_id'), 'site_rag_sources', ['page_id'], unique=False)
    op.create_index(op.f('ix_site_rag_sources_response_id'), 'site_rag_sources', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_rag_sources_response_id'), table_name='site_rag_sources')
    op.drop_index(op.f('ix_site_rag_sources_page_id'), table_name='site_rag_sources')
    op.drop_table('site_rag_sources')
    # ### end Alembic commands ###
