"""add websites and pages

Revision ID: b458996b8533
Revises: df9cc2b84465
Create Date: 2026-08-23 23:06:23.401991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b458996b8533'
down_revision: Union[str, Sequence[str], None] = 'df9cc2b84465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'domain', name='uq_brand_domain')
    )
    op.create_index(op.f('ix_websites_brand_id'), 'websites', ['brand_id'], unique=False)
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('robots_meta', sa.String(length=255), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('internal_link_count', sa.Integer(), nullable=False),
    sa.Column('external_link_count', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'url', name='uq_website_page_url')
    )
    op.create_index(op.f('ix_pages_website_id'), 'pages', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_website_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_index(op.f('ix_websites_brand_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
