"""add persistent entity resolution and run measurement metadata

Revision ID: b4c33149f865
Revises: 16e231176d65
Create Date: 2026-08-24 10:21:29.074188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c33149f865'
down_revision: Union[str, Sequence[str], None] = '16e231176d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_resolution_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'normalized_name', name='uq_project_entity_resolution')
    )
    op.create_index(op.f('ix_entity_resolution_rules_brand_id'), 'entity_resolution_rules', ['brand_id'], unique=False)
    op.create_index(op.f('ix_entity_resolution_rules_normalized_name'), 'entity_resolution_rules', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_entity_resolution_rules_project_id'), 'entity_resolution_rules', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_resolution_rules_status'), 'entity_resolution_rules', ['status'], unique=False)
    op.add_column('ai_runs', sa.Column('run_type', sa.String(length=30), server_default='ad_hoc', nullable=False))
    op.add_column('ai_runs', sa.Column('include_in_metrics', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_ai_runs_include_in_metrics'), 'ai_runs', ['include_in_metrics'], unique=False)
    op.create_index(op.f('ix_ai_runs_run_type'), 'ai_runs', ['run_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_runs_run_type'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_include_in_metrics'), table_name='ai_runs')
    op.drop_column('ai_runs', 'include_in_metrics')
    op.drop_column('ai_runs', 'run_type')
    op.drop_index(op.f('ix_entity_resolution_rules_status'), table_name='entity_resolution_rules')
    op.drop_index(op.f('ix_entity_resolution_rules_project_id'), table_name='entity_resolution_rules')
    op.drop_index(op.f('ix_entity_resolution_rules_normalized_name'), table_name='entity_resolution_rules')
    op.drop_index(op.f('ix_entity_resolution_rules_brand_id'), table_name='entity_resolution_rules')
    op.drop_table('entity_resolution_rules')
    # ### end Alembic commands ###
