"""add web search source evidence

Revision ID: d078c217bc8d
Revises: 63ba5d94da09
Create Date: 2026-08-24 14:03:19.457008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd078c217bc8d'
down_revision: Union[str, Sequence[str], None] = '63ba5d94da09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_search_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('search_call_index', sa.Integer(), nullable=False),
    sa.Column('source_position', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('is_cited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'search_call_index', 'source_position', name='uq_web_search_source_position')
    )
    op.create_index(op.f('ix_web_search_sources_brand_id'), 'web_search_sources', ['brand_id'], unique=False)
    op.create_index(op.f('ix_web_search_sources_domain'), 'web_search_sources', ['domain'], unique=False)
    op.create_index(op.f('ix_web_search_sources_is_cited'), 'web_search_sources', ['is_cited'], unique=False)
    op.create_index(op.f('ix_web_search_sources_response_id'), 'web_search_sources', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_search_sources_response_id'), table_name='web_search_sources')
    op.drop_index(op.f('ix_web_search_sources_is_cited'), table_name='web_search_sources')
    op.drop_index(op.f('ix_web_search_sources_domain'), table_name='web_search_sources')
    op.drop_index(op.f('ix_web_search_sources_brand_id'), table_name='web_search_sources')
    op.drop_table('web_search_sources')
    # ### end Alembic commands ###
