"""add geo prompts engines models and runs

Revision ID: d3aa2688307b
Revises: 7708e4ae926d
Create Date: 2026-08-24 00:26:52.710678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3aa2688307b'
down_revision: Union[str, Sequence[str], None] = '7708e4ae926d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ai_engines_slug'), 'ai_engines', ['slug'], unique=True)
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider_model_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['ai_engines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_id', 'provider_model_id', name='uq_engine_provider_model')
    )
    op.create_index(op.f('ix_ai_models_engine_id'), 'ai_models', ['engine_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.create_index(op.f('ix_prompts_intent'), 'prompts', ['intent'], unique=False)
    op.create_index(op.f('ix_prompts_project_id'), 'prompts', ['project_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_model_id'), 'ai_runs', ['model_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_project_id'), 'ai_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_prompt_id'), 'ai_runs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_status'), 'ai_runs', ['status'], unique=False)
    op.create_table('ai_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_responses_run_id'), 'ai_responses', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_responses_run_id'), table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index(op.f('ix_ai_runs_status'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_prompt_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_project_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_model_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_prompts_project_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_intent'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_ai_models_engine_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_ai_engines_slug'), table_name='ai_engines')
    op.drop_table('ai_engines')
    # ### end Alembic commands ###
