"""add site rag gaps

Revision ID: e60ffab4e9c6
Revises: af134a8ac2c9
Create Date: 2026-08-27 08:17:58.712721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60ffab4e9c6'
down_revision: Union[str, Sequence[str], None] = 'af134a8ac2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_rag_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('target_brand_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('answerable_runs', sa.Integer(), nullable=False),
    sa.Column('unsupported_runs', sa.Integer(), nullable=False),
    sa.Column('answerability_rate', sa.Float(), nullable=False),
    sa.Column('unsupported_rate', sa.Float(), nullable=False),
    sa.Column('gap_type', sa.String(length=60), nullable=False),
    sa.Column('gap_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['geo_experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'prompt_id', name='uq_site_rag_gap_experiment_prompt')
    )
    op.create_index(op.f('ix_site_rag_gaps_category'), 'site_rag_gaps', ['category'], unique=False)
    op.create_index(op.f('ix_site_rag_gaps_experiment_id'), 'site_rag_gaps', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_site_rag_gaps_gap_type'), 'site_rag_gaps', ['gap_type'], unique=False)
    op.create_index(op.f('ix_site_rag_gaps_priority'), 'site_rag_gaps', ['priority'], unique=False)
    op.create_index(op.f('ix_site_rag_gaps_project_id'), 'site_rag_gaps', ['project_id'], unique=False)
    op.create_index(op.f('ix_site_rag_gaps_prompt_id'), 'site_rag_gaps', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_site_rag_gaps_target_brand_id'), 'site_rag_gaps', ['target_brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_rag_gaps_target_brand_id'), table_name='site_rag_gaps')
    op.drop_index(op.f('ix_site_rag_gaps_prompt_id'), table_name='site_rag_gaps')
    op.drop_index(op.f('ix_site_rag_gaps_project_id'), table_name='site_rag_gaps')
    op.drop_index(op.f('ix_site_rag_gaps_priority'), table_name='site_rag_gaps')
    op.drop_index(op.f('ix_site_rag_gaps_gap_type'), table_name='site_rag_gaps')
    op.drop_index(op.f('ix_site_rag_gaps_experiment_id'), table_name='site_rag_gaps')
    op.drop_index(op.f('ix_site_rag_gaps_category'), table_name='site_rag_gaps')
    op.drop_table('site_rag_gaps')
    # ### end Alembic commands ###
