"""add brand mentions and citations

Revision ID: f443a7baebe9
Revises: d3aa2688307b
Create Date: 2026-08-24 01:08:48.533179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f443a7baebe9'
down_revision: Union[str, Sequence[str], None] = 'd3aa2688307b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('mention_text', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('is_target', sa.Boolean(), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_mentions_brand_id'), 'brand_mentions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_mentions_normalized_name'), 'brand_mentions', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_brand_mentions_response_id'), 'brand_mentions', ['response_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_brand_id'), 'citations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_citations_domain'), 'citations', ['domain'], unique=False)
    op.create_index(op.f('ix_citations_response_id'), 'citations', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_response_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_domain'), table_name='citations')
    op.drop_index(op.f('ix_citations_brand_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_brand_mentions_response_id'), table_name='brand_mentions')
    op.drop_index(op.f('ix_brand_mentions_normalized_name'), table_name='brand_mentions')
    op.drop_index(op.f('ix_brand_mentions_brand_id'), table_name='brand_mentions')
    op.drop_table('brand_mentions')
    # ### end Alembic commands ###
